version: '3.7'
# networks: 
#   opentechiz:
#     external: true
#     driver: overlay
services:
    kma-gear-backend:
        build:
            context: ./
            target: development

        env_file:
            - .env
        volumes:
            - ./:/usr/src/app
        ports:
            - 8080:8080
        restart: always
        depends_on:
            - postgres
    postgres:
        image: postgres
        restart: always
        volumes:
            - PostgresKmaGearDB:/data/db
            - PostgresBackup:/opt/backup
        environment:
            POSTGRES_PASSWORD: root

volumes:
    PostgresKmaGearDB:
    PostgresBackup:
